#!/bin/sh
sequel_aux=.sqlaux

test -d $sequel_aux
case $? in
    0) ;;
    1) mkdir $sequel_aux ;;
esac

sequel_lib=.sqllib

test -d $sequel_lib
case $? in
    0) ;;
    1) mkdir $sequel_lib ;;
esac

cp -u $HOME/sequel_fixed/lib2cpp/*.lst $sequel_aux/.
cp -u $HOME/sequel_fixed/lib2cpp/*.lib $sequel_lib/.
cp -u $HOME/sequel_fixed/exec/tmpdim.in .
cp $* $sequel_aux/cct.in
$HOME/sequel_fixed/exec/sqlcppprep_fixed_static
$HOME/sequel_fixed/exec/sqlcppmain_fixed_static
